### ISSUE TITLE
Crash in custom input style

### ISSUE THREAD

**Issue by licaon-kter** [rkkr/simple-keyboard#100]
AOSP Pie, 3.7 F-Droid

Go to "Appearance & Layouts" -> "Custom Input Styles"

First of all it doesn't have the usual German/French entries, it has a "." (dot) instead.

And when you try to enter and setup one you'll get:
```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: rkr.simplekeyboard.inputmethod, PID: 15942
E AndroidRuntime: android.content.res.Resources$NotFoundException: String resource ID #0x0
E AndroidRuntime: 	at android.content.res.Resources.getText(Resources.java:348)
E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:441)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.d.n.a(Unknown Source:6)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.d.n.a(Unknown Source:0)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.d.m.a(Unknown Source:44)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.d.p.a(Unknown Source:64)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.d.p.e(Unknown Source:8)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.settings.f$f.<init>(Unknown Source:11)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.settings.f$e.<init>(Unknown Source:44)
E AndroidRuntime: 	at rkr.simplekeyboard.inputmethod.latin.settings.CustomInputStyleSettingsFragment.onActivityCreated(Unknown Source:6)
E AndroidRuntime: 	at android.app.Fragment.performActivityCreated(Fragment.java:2531)
E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318)
E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6723)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Going back to 3.6 it works fine.

**Comment by licaon-kter** [comment]
I'll close this then

**Comment by Translator5** [comment]
Is this the same Error?

How to fix it?

[Gist](https://gist.github.com/Translator5/f13e93a76199a7c0b5b5dd4499bced71)

**Comment by rkkr** [comment]
Nope, this is not the same. What exactly did you do to get it?

**Comment by Translator5** [comment]
> Nope, this is not the same. What exactly did you do to get it?

Nothing special, just created a new layout 'miroslavic' using a language group (called 'sla' in my list).
On switching to the layout simple keyboard crashes and gives that output.

My edits are viewable here; [GitLab](https://gitlab.com/Translator5/simple-keyboard/commits/master) Just the 6 Commits of 29 Nov, 2018.

**Comment by licaon-kter** [comment]
@Translator5 Since you are modifying the app maybe open a new issue instead.
