### ISSUE TITLE
[ver 5.0][crash] custom input styles

### ISSUE THREAD

**Issue by disdaogitacc** [rkkr/simple-keyboard#280]
hi and thanks for making the app tho.

simple keyboard > appearance & layouts > custom input styles and BOOM "unfortunately the simple keyboard has stopped"

**my device information:**
LG G4 H818P
android version 7.0
rooted: no
screen density: 544 dpi
keyboard language switches between English(US) and Persian
System default language: English(US)

**Comment by rkkr** [comment]
@wittmane this one seems to be yours. Only crashes on older androids. Tested in locally 4.4.

```
rkr.simplekeyboard.inputmethod E/AndroidRuntime: FATAL EXCEPTION: main
    Process: rkr.simplekeyboard.inputmethod, PID: 2276
    java.lang.RuntimeException: Unable to start activity ComponentInfo{rkr.simplekeyboard.inputmethod/rkr.simplekeyboard.inputmethod.latin.settings.SettingsActivity}: java.lang.IllegalArgumentException: Invalid fragment for this activity: rkr.simplekeyboard.inputmethod.latin.settings.CustomInputStyleSettingsFragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: Invalid fragment for this activity: rkr.simplekeyboard.inputmethod.latin.settings.CustomInputStyleSettingsFragment
        at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1180)
        at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1199)
        at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:545)
        at rkr.simplekeyboard.inputmethod.latin.settings.SettingsActivity.onCreate(SettingsActivity.java:76)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method)
```

**Comment by rkkr** [comment]
Removal of `sLatinImeFragments.add(CustomInputStyleSettingsFragment.class.getName());` in `FragmentUtils.java` seems to be the cause.

**Comment by wittmane** [comment]
@rkkr Yeah, I think that's the issue. I didn't mean to remove that. I must have missed that when I reverted part of my PR.

I can't really work on this today, but I should be able to verify the solution and make a PR tomorrow if you don't just fix it first.

**Comment by rkkr** [comment]
No rush. I'll have to cleanup the Turkish F anyways...
